# Generated by Django 3.2.4 on 2021-06-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(default='Name', max_length=256, verbose_name='Product Name')),
                ('SKU', models.CharField(default='SKU', max_length=128, verbose_name='Product SKU')),
                ('BotanicalName', models.CharField(default='Botanical Name', max_length=256)),
                ('PlantPartUsed', models.CharField(default='Plant Part', max_length=256)),
                ('ProcessingMethod', models.CharField(default='Processing Method', max_length=512)),
                ('ProductType', models.CharField(default='Product Type', max_length=128)),
                ('Description', models.TextField(default='Description', max_length=10000)),
            ],
        ),
    ]
