# Generated by Django 3.2.4 on 2021-06-14 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='SubCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.subcategory'),
        ),
    ]
