# Generated by Django 3.2.4 on 2021-06-22 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210619_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.TextField(blank=True, default='Description', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ShelfLife',
            field=models.CharField(blank=True, default='1', max_length=10, null=True, verbose_name='Self Life in Months'),
        ),
        migrations.AlterField(
            model_name='product',
            name='SubCategory',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.subcategory'),
        ),
    ]
