# Generated by Django 3.2.4 on 2021-06-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210622_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='BotanicalName',
            field=models.CharField(blank=True, default='Botanical Name', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='PlantPartUsed',
            field=models.CharField(blank=True, default='Plant Part', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProcessingMethod',
            field=models.CharField(blank=True, default='Processing Method', max_length=512, null=True),
        ),
    ]
