# Generated by Django 3.2.4 on 2021-06-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210622_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank=True, default='product_images/alt.png', null=True, upload_to='product_images/'),
        ),
    ]
