# Generated by Django 3.2.4 on 2021-08-11 15:24

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_view_ips_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('Name', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=500)),
                ('Query', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Queries',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='ShelfLife',
            field=models.CharField(blank=True, default='1', max_length=10, null=True, verbose_name='Shelf Life in Months'),
        ),
    ]
