# Generated by Django 3.2.4 on 2021-12-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210811_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField()),
            ],
            options={
                'verbose_name': 'About Us Section',
                'verbose_name_plural': 'About Us Section',
            },
        ),
    ]
